artifact_uri: file:C:/Users/Danny/Desktop/Computer Science/FSE/Final Project/heart-beat/heart_beat_model/mlflow_tracking/artifacts/339102042405170477/5a75bea46a2f4b8d86626738b38122bd/artifacts
end_time: 1757685590541
entry_point_name: ''
experiment_id: '339102042405170477'
lifecycle_stage: active
run_id: 5a75bea46a2f4b8d86626738b38122bd
run_name: CVM_ovo_cv10fold
source_name: ''
source_type: 4
source_version: ''
start_time: 1757685296168
status: 3
tags: []
user_id: Danny
