digest: 3318030d
name: dataset
profile: '{"features_shape": [5, 4], "features_size": 20, "features_nbytes": 160}'
schema: '{"mlflow_tensorspec": {"features": "[{\"type\": \"tensor\", \"tensor-spec\":
  {\"dtype\": \"float64\", \"shape\": [-1, 4]}}]", "targets": null}}'
source: '{"tags": {"mlflow.user": "Danny", "mlflow.source.name": "stress_model.py",
  "mlflow.source.type": "LOCAL", "mlflow.source.git.commit": "fa18723edab4425200b66da517b61b30182624cf"}}'
source_type: code
