services:
  backend:
    build: ./heart_beat_server
    ports:
      - "4000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345
      - DB_NAME=heartbeat_db
    volumes:
      - ./heart_beat_server:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "./wait-for-it.sh postgres:5432 --timeout=30 --strict -- \
           npx typeorm-ts-node-commonjs migration:run -d dist/data-source.js && \
           npm run seed && \
           npm run start:dev"

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=heartbeat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
