aliases: []
creation_timestamp: 1757684416459
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1757684416459
metrics: null
model_id: m-465eee1a569248fba40d16169640609b
name: svm_ovo_best_model
params: null
run_id: d37a8ff219b641068caf1157eb555631
run_link: ''
source: models:/m-465eee1a569248fba40d16169640609b
status: READY
status_message: null
storage_location: file:C:/Users/Danny/Desktop/Computer Science/FSE/Final Project/heart-beat/heart_beat_model/mlflow_tracking/artifacts/339102042405170477/models/m-465eee1a569248fba40d16169640609b/artifacts
user_id: null
version: 1
