aliases: []
creation_timestamp: 1757684821548
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1757684821548
metrics: null
model_id: m-872c35d1c957430484c3634237d10249
name: svm_ovo_best_model
params: null
run_id: e0cf1dc1d3be48cfb2387fb4698b9bc8
run_link: ''
source: models:/m-872c35d1c957430484c3634237d10249
status: READY
status_message: null
storage_location: file:C:/Users/Danny/Desktop/Computer Science/FSE/Final Project/heart-beat/heart_beat_model/mlflow_tracking/artifacts/339102042405170477/models/m-872c35d1c957430484c3634237d10249/artifacts
user_id: null
version: 2
