export const referenceEntries: Record<string, string[]> = {
  Happy: [
    'I had a wonderful day at the park with my friends.',
    'Sunshine and laughter filled my afternoon.',
    'I finally finished my painting and I feel proud.',
    'My cat did something funny and made me laugh.',
    'I met an old friend and it felt amazing.',
    'The coffee was perfect and my day started well.',
    'I danced to my favorite song without a care.',
    'The flowers in the garden made me smile.',
    'I got a compliment at work and felt appreciated.',
    "A stranger's kindness brightened my whole day.",
  ],
  Sad: [
    'I felt a deep loneliness after everyone left.',
    'The rainy weather made me stay in bed all day.',
    "I lost something valuable and I can't stop thinking about it.",
    'I watched an emotional movie and cried quietly.',
    "Missing my family is hard when I'm far from home.",
    'I felt disconnected from the world today.',
    'I remembered a painful memory and it hurt.',
    'My favorite book reminded me of better times.',
    "I got bad news and couldn't focus on anything else.",
    "I wanted to reach out to someone but didn't.",
  ],
  Calm: [
    'Sitting by the lake, I felt completely at ease.',
    'Meditation this morning helped me clear my mind.',
    'I enjoyed a warm bath and soft music tonight.',
    'I read quietly while the rain fell outside.',
    'A slow walk in the park made me feel relaxed.',
    'I spent the evening sketching and felt serene.',
    'Listening to classical music brought peace.',
    'I brewed tea and just sat, enjoying the silence.',
    'Watching the sunset calmed my thoughts.',
    'The gentle breeze on my balcony felt soothing.',
  ],
  Focus: [
    'I completed all my work tasks without distraction.',
    'Studying in the library helped me concentrate deeply.',
    'I planned my week carefully and stuck to the schedule.',
    'Writing in my journal helped me organize my thoughts.',
    'I solved a complex problem without interruptions.',
    'I read and understood a difficult article thoroughly.',
    'I cleaned and organized my desk to stay on track.',
    'I concentrated on painting details and lost track of time.',
    'I followed my workout plan attentively.',
    'I focused on learning new skills and felt productive.',
  ],
  Energetic: [
    'I went for a long run and felt alive.',
    'Dancing around my room lifted my spirits.',
    'I completed all my errands quickly with energy to spare.',
    'I joined a spontaneous game with friends and had fun.',
    'I felt a burst of creativity while drawing.',
    'I tackled a big cleaning project today.',
    'I was motivated to cook a new recipe and enjoyed it.',
    'I felt ready to take on any challenge.',
    'I played my favorite sport and felt unstoppable.',
    'I jumped on my bike and explored the neighborhood.',
  ],
  Angry: [
    'Someone cut me off in traffic and I got furious.',
    'A coworker took credit for my idea and I felt enraged.',
    'I argued with a friend and slammed the door.',
    'Waiting in line made me feel impatient and mad.',
    'I spilled coffee on my shirt and it ruined my mood.',
    'My computer crashed during an important task.',
    'I was frustrated when plans changed unexpectedly.',
    'Noise from neighbors annoyed me all day.',
    'I felt irritation building while stuck in traffic.',
    'Someone ignored my messages and I got upset.',
  ],
  Anxious: [
    "I can't stop thinking about the looming deadlines.",
    'My heart races every time I think of the meeting.',
    'I worry about small things constantly today.',
    'I felt tense walking into the crowded room.',
    'I kept imagining worst-case scenarios at work.',
    'I woke up thinking about everything I have to do.',
    'I felt jittery after reading some bad news.',
    'I hesitated before making even small decisions.',
    'I kept checking my phone nervously.',
    'My stomach was tight from nerves all day.',
  ],
  Tired: [
    'I barely slept last night and feel drained.',
    'My body aches and I want to rest all day.',
    'After working non-stop, I can barely focus.',
    'I fell asleep on the couch after dinner.',
    'I feel too exhausted to cook or clean.',
    'I struggled to get out of bed this morning.',
    "My energy is low and I can't concentrate.",
    'I took a long nap but still feel sleepy.',
    'I yawned constantly during my meeting.',
    "I feel worn out from the week's activities.",
  ],
  Lonely: [
    'I spent the evening alone and felt disconnected.',
    'No one called me today and it was quiet.',
    'I wished someone was here to talk to.',
    'I sat by the window watching others pass by.',
    'I felt isolated even in the crowded room.',
    'Scrolling through social media made me sad.',
    'I missed having company during lunch.',
    'The silence at home felt heavy today.',
    "I longed for a friend's presence.",
    'I felt like an outsider among my peers.',
  ],
  Excited: [
    "I can't wait for the concert tonight!",
    'Planning my trip next week has me buzzing.',
    "I got tickets to the show I've wanted for months.",
    'I received an unexpected gift and felt thrilled.',
    "I'm looking forward to seeing my family soon.",
    "I'm eager to start a new project at work.",
    "I found out some great news and can't stop smiling.",
    'I woke up feeling energetic and ready for today.',
    'I met someone new and it felt exhilarating.',
    "I'm counting down to the weekend activities.",
  ],
  Frustrated: [
    "The project isn't going as planned and I'm annoyed.",
    'I tried fixing the bug but failed repeatedly.',
    'Assembling the furniture was a nightmare today.',
    "I can't get my ideas across in the meeting.",
    "I feel stuck and don't know what to do next.",
    'I lost my notes and now I have to redo everything.',
    'The slow internet makes me want to scream.',
    "I argued with a colleague and it didn't resolve.",
    "My plans keep getting delayed and it's irritating.",
    'I feel like nothing is working out today.',
  ],
  Hopeful: [
    'I believe things will get better soon.',
    'I feel optimistic about the next steps in my life.',
    'I see potential in the challenges ahead.',
    "I'm planning for the future with confidence.",
    'I think today could be a turning point.',
    'I feel motivated to improve myself.',
    'I trust that solutions will appear in time.',
    "I'm inspired by the progress I've made.",
    'I feel positive about upcoming opportunities.',
    "I'm hopeful that my efforts will pay off.",
  ],
};
