artifact_location: file:C:/Users/Danny/Desktop/Computer Science/FSE/Final Project/heart-beat/heart_beat_model/mlflow_tracking/artifacts/339102042405170477/models/m-2fce512dcc0b4006ad32df59ddf9d556/artifacts
creation_timestamp: 1757685580460
experiment_id: '339102042405170477'
last_updated_timestamp: 1757685590198
model_id: m-2fce512dcc0b4006ad32df59ddf9d556
model_type: ''
name: svm_ovo_best_model
source_run_id: 5a75bea46a2f4b8d86626738b38122bd
status: 2
status_message: null
