name: Heart-Beat CD

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            # -----------------------------
            APP_DIR=/home/ubuntu/heart-beat
            mkdir -p $APP_DIR
            cd $APP_DIR

            mkdir -p ~/.ssh
            echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
            chmod 600 ~/.ssh/deploy_key
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            export GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key -o IdentitiesOnly=yes"

            if [ -d ".git" ]; then
              git reset --hard
              git pull origin main
            else
              git clone git@github.com:Daniel-Hayek/heart-beat.git .
            fi

            rm -rf heart_beat_client/

            docker-compose down -v

            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            
            docker system prune -af --volumes
            
            docker-compose up --build -d
